import PremiumPage from "@/components/premium/premiumPage";
import { subscription } from "@/services/AuthService";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetGrub | Premium",
  description: "Generated by streetGrub Premium page",
};
const Premium = async () => {
  const payment = await subscription();
  return (
    <div>
      <PremiumPage payment={payment.data} />
    </div>
  );
};

export default Premium;
