import AboutPage from "@/components/page/about/AboutPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "StreetGrub | About",
  description: "Generated by streetGrub About page",
};
const About = () => {
  return (
    <div>
      <AboutPage />
    </div>
  );
};

export default About;
