import Comments from "@/components/page/Dashbaord/Comments";
import { getComments } from "@/services/commentservice";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "StreetGrub | Dashbaord - Comments",
  description: "Generated by streetGrub Dashbaord - Comments page",
};
const Comment = async () => {
  const comments = await getComments();
  console.log(comments);
  return (
    <div>
      <Comments Postcomments={comments?.data} />
    </div>
  );
};

export default Comment;
