import Dashboard from "@/components/page/Dashbaord/Dashboard";
import { dashbaordOverview } from "@/services/AuthService";
import { getAllPostForAdmin } from "@/services/postService";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetGrub | Home",
  description: "Generated by streetGrub Home page",
};
const Dashbaord = async () => {
  const res = await getAllPostForAdmin();
  const result = await dashbaordOverview();
  return (
    <div>
      <Dashboard
        mockStats={result?.data?.summary}
        posts={res?.data}
        data={result?.data?.monthlyStats}
      />
    </div>
  );
};

export default Dashbaord;
