import Dashboard from "@/components/page/Dashbaord/Dashboard";
import { getAllPostForAdmin } from "@/services/postService";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetGrub | Home",
  description: "Generated by streetGrub Home page",
};
const Dashbaord = async () => {
  const res = await getAllPostForAdmin();
  return (
    <div>
      <Dashboard posts={res.data} />
    </div>
  );
};

export default Dashbaord;
