import Categories from "@/components/page/Dashbaord/Categories";
import { getAllcategory } from "@/services/categoryservice";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetGrub | Dashbaord - Category",
  description: "Generated by streetGrub  Dashbaord - Category page",
};
const Category = async () => {
  const result = await getAllcategory();
  return (
    <div>
      <Categories initialCategories={result?.data} />
    </div>
  );
};

export default Category;
