import Analytics from "@/components/page/Dashbaord/Analytics";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "StreetGrub | Dashbaord - Analytics",
  description: "Generated by streetGrub  Dashbaord - Analytics page",
};
const Analytic = () => {
  return (
    <div>
      <Analytics />
    </div>
  );
};

export default Analytic;
